language: cpp

matrix:
  include:
  - os: linux
    env: ARCH=x86_64
    compiler: gcc
    sudo: require
    dist: xenial
  - os: osx
    osx_image: xcode10.3
    before_cache:
      - brew cleanup
    cache:
      directories:
        - $HOME/Library/Caches/Homebrew
    addons:
      homebrew:
        packages:
        - ffmpeg
        - qt5
        - grep
        - opencolorio
        - openimageio
        update: true
  # Can't build on Windows - affected by https://travis-ci.community/t/current-known-issues-please-read-this-before-posting-a-new-topic/264/10
  # - os: windows

before_install:
  - source ./.travis/before_install.sh

install:
  - source ./.travis/install.sh

script:
  - source ./.travis/script.sh

after_success:
  - source ./.travis/after_success.sh
  
branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/    
